# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
---
name: Go

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['master', 'develop']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.20', '1.21.x', '1.22.x', '1.23.x', '1.24.x']
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-tags: 'true'
          fetch-depth: '20'

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        run: go build -v ./...

      - name: Build binary
        run: GOOS=linux GOARCH=arm64 make
